71-expose git commit hash as environment variable in bodywork containers to help with versioning
bodywork-ml/bodywork-core pull request #84
Opened 2021-05-13 13:31 UTC by Marios85

This PR close #71. The commit hash is retrieved and added to both batch and service stages. 

Some refactoring was also done in `workflow_execution.py` which consisted of breaking down the `run_workflow` method into smaller units.

2021-05-14 18:57 UTC, AlexIoannides commented on src/bodywork/workflow_execution.py
> +    namespace,
Missing type hint.

2021-05-14 18:58 UTC, AlexIoannides commented on src/bodywork/workflow_execution.py
> +    repo_branch,
Missing type hint.

2021-05-14 19:07 UTC, AlexIoannides requested changes
This is 1st class!

I even learnt something about mocking unit tests in `test_run_workflow_adds_git_commit_to_batch_and_service_env_vars`.

Super-trivial request - there are a couple of missing type definitions. I have no idea how they were allows to slip through...

2021-05-14 19:10 UTC, AlexIoannides commented
To prevent the typing issue from happening again, could you add the following to `mypy.ini`:

```ini
[mypy]
...
disallow_untyped_calls=True
disallow_untyped_defs=True
```

I think that should do it.

2021-05-14 19:11 UTC, AlexIoannides commented
I've only just noticed that you can click-through on the CodeCov link to get a full report - e.g. [here](https://app.codecov.io/gh/bodywork-ml/bodywork-core/compare/84/diff#diff-c3JjL2JvZHl3b3JrL2dpdC5weQ==). Might be worth a look.

2021-05-14 19:17 UTC, AlexIoannides commented
Would you mind adding a quick test for `get_git_commit_hash` raising a `RuntimeError` if the sub-process fails?

2021-05-15 11:07 UTC, Marios85 commented
I've made all the changes above. I thought you might ask for the exception test for the CodeCov badge. 

The new MyPy rules threw up a lot of errors so I had to fix them in various files if you are wondering why this PR has now touched so many files.

2021-05-15 11:08 UTC, merged